# Generated by Django 5.2.15 on 2026-08-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='district',
            field=models.CharField(blank=True, choices=[('1010', '1010 — Innere Stadt'), ('1020', '1020 — Leopoldstadt'), ('1030', '1030 — Landstraße'), ('1040', '1040 — Wieden'), ('1050', '1050 — Margareten'), ('1060', '1060 — Mariahilf'), ('1070', '1070 — Neubau'), ('1080', '1080 — Josefstadt'), ('1090', '1090 — Alsergrund'), ('1100', '1100 — Favoriten'), ('1110', '1110 — Simmering'), ('1120', '1120 — Meidling'), ('1130', '1130 — Hietzing'), ('1140', '1140 — Penzing'), ('1150', '1150 — Rudolfsheim-Fünfhaus'), ('1160', '1160 — Ottakring'), ('1170', '1170 — Hernals'), ('1180', '1180 — Währing'), ('1190', '1190 — Döbling'), ('1200', '1200 — Brigittenau'), ('1210', '1210 — Floridsdorf'), ('1220', '1220 — Donaustadt'), ('1230', '1230 — Liesing')], max_length=4),
        ),
    ]
