# Generated by Django 5.2.15 on 2026-06-18 12:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('sport', models.CharField(max_length=50)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('all', 'All levels')], default='all', max_length=20)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('location_name', models.CharField(max_length=255)),
                ('location_address', models.CharField(blank=True, max_length=512)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('max_slots', models.PositiveIntegerField(default=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_at'],
            },
        ),
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('attending', 'Attending'), ('waiting', 'Waiting')], max_length=20)),
                ('queue_position', models.PositiveIntegerField(default=0)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['status', 'queue_position', 'joined_at'],
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['sport'], name='events_even_sport_c790f5_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['start_at'], name='events_even_start_a_268ef9_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['level'], name='events_even_level_22f2a0_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventparticipant',
            constraint=models.UniqueConstraint(fields=('user', 'event'), name='unique_user_event_participation'),
        ),
        migrations.AddConstraint(
            model_name='eventparticipant',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'waiting')), fields=('event', 'queue_position'), name='unique_waiting_position_per_event'),
        ),
    ]
