# Generated by Django 5.2.15 on 2026-06-19 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='max_slots',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
