# Generated by Django 5.2.16 on 2026-08-05 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("friend_request", "Friend request"),
                    ("friend_accepted", "Friend request accepted"),
                    ("direct_message", "Direct message"),
                ],
                max_length=32,
            ),
        ),
    ]
