# Generated by Django 5.2.9 on 2026-08-04 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('blocked', 'Blocked')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendship_requests_created', to=settings.AUTH_USER_MODEL)),
                ('user_high', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships_as_high', to=settings.AUTH_USER_MODEL)),
                ('user_low', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships_as_low', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user_low', 'status'], name='social_friend_low_status'), models.Index(fields=['user_high', 'status'], name='social_friend_high_status'), models.Index(fields=['requested_by', 'status'], name='social_friend_requester_status')],
                'constraints': [models.UniqueConstraint(fields=('user_low', 'user_high'), name='social_unique_friendship_pair'), models.CheckConstraint(condition=models.Q(('user_low', models.F('user_high')), _negated=True), name='social_friendship_users_differ'), models.CheckConstraint(condition=models.Q(('requested_by', models.F('user_low')), ('requested_by', models.F('user_high')), _connector='OR'), name='social_requester_is_participant')],
            },
        ),
    ]
