# Generated by Django 5.2.9 on 2026-08-04 14:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='friendship',
            constraint=models.CheckConstraint(condition=models.Q(('user_low_id__lt', models.F('user_high_id'))), name='social_friendship_pair_is_canonical'),
        ),
    ]
