# Generated by Django 5.2.15 on 2026-06-22 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_geocodecache_is_final_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='geocodecache',
            new_name='geo_geocode_provide_52b167_idx',
            old_name='geo_geocod_provider_b9ebfb_idx',
        ),
        migrations.RenameIndex(
            model_name='geocodecache',
            new_name='geo_geocode_provide_10d827_idx',
            old_name='geo_geocod_provider_4d7309_idx',
        ),
        migrations.RenameIndex(
            model_name='geocodecache',
            new_name='geo_geocode_query_n_14aec4_idx',
            old_name='geo_geocod_query_n_8c0b6f_idx',
        ),
        migrations.RenameIndex(
            model_name='geocodecache',
            new_name='geo_geocode_expires_b14540_idx',
            old_name='geo_geocod_expires__31f9e8_idx',
        ),
    ]
